"""qtools.tomo - Quantum State Tomography and Polarization Entanglement Toolkit.

Powered by QuTiP.
"""

from __future__ import annotations

from qtools.tomo import bell, bosonic, tomography
from qtools.tomo.bell import (
    a_state,
    basis_states,
    bell_state,
    bell_states,
    bipartite_projector,
    calculate,
    chsh_correlation,
    chsh_measurements,
    chsh_probabilities,
    chsh_scan,
    chsh_value,
    circ_to_lin_matrix,
    concurrence,
    conditional_probability,
    convert_basis,
    d_state,
    density_matrix,
    format_state_amplitudes,
    h_state,
    hwp,
    hwp_analyzer_basis,
    hwp_to_polarization_angle,
    joint_probability,
    l_state,
    lin_to_circ_matrix,
    linear_polarization,
    marginal_probability,
    orthogonal_polarization,
    parametric_bell_state,
    phase_scan,
    polarization_angle_to_hwp,
    polarization_basis,
    polarization_observable,
    polarizer,
    post_measurement_state,
    projector,
    qwp,
    r_state,
    rotation_matrix,
    scan_angles,
    state_from_amplitudes,
    to_circular_basis,
    to_hv_basis,
    v_state,
    werner_state,
)

__all__ = [
    "bell",
    "bosonic",
    "tomography",
    # Polarization & Jones
    "h_state",
    "v_state",
    "d_state",
    "a_state",
    "r_state",
    "l_state",
    "linear_polarization",
    "orthogonal_polarization",
    "polarization_basis",
    "basis_states",
    "rotation_matrix",
    "hwp",
    "qwp",
    "polarizer",
    "hwp_to_polarization_angle",
    "polarization_angle_to_hwp",
    "hwp_analyzer_basis",
    # Basis transformations
    "circ_to_lin_matrix",
    "lin_to_circ_matrix",
    "convert_basis",
    "to_hv_basis",
    "to_circular_basis",
    # States & Bell
    "bell_state",
    "bell_states",
    "parametric_bell_state",
    "density_matrix",
    "werner_state",
    "state_from_amplitudes",
    "concurrence",
    # Projective measurements
    "projector",
    "bipartite_projector",
    "marginal_probability",
    "joint_probability",
    "conditional_probability",
    "post_measurement_state",
    # CHSH tests
    "polarization_observable",
    "chsh_correlation",
    "chsh_probabilities",
    "chsh_value",
    "chsh_measurements",
    "chsh_scan",
    # Simulation
    "calculate",
    "scan_angles",
    "format_state_amplitudes",
    "phase_scan",
]
