import os
from pathlib import Path

MY_DOCUMENTS = Path(os.path.expanduser("~")) / "Documents"

ACQU_SIGNAL_GEN = "GEN8"
ACQU_SIGNAL_TSCO = "TSCO9"
ACQU_SIGNAL_DELA = "DELA8"
HIST_NONE_REF_TSCO = "TSCO10"

RAW_FORMAT_BIN = "bin"
RAW_FORMAT_TXT = "ascii"
RAW_FORMATS = {RAW_FORMAT_BIN: "bin", RAW_FORMAT_TXT: "txt"}

HISTO_FORMAT_CSV = "csv"
HISTO_FORMAT_PDF = "pdf"
HISTO_FORMATS = {HISTO_FORMAT_CSV: "csv", HISTO_FORMAT_PDF: "pdf"}

LATENCY_HR = 800000
LATENCY_HS = 400000

NUMERATOR_HR = 1
NUMERATOR_HS = 100

GEN_DELAY_MIN = 4000
GEN_DELAY_MAX = 3600000000000

INACTIVITY_TIMEOUT = 10
