from abc import ABC
from typing import Union

import numpy.typing as npt

from slmutils.typing import PathLike

__all__ = [
    "DisplayInterface",
]


class DisplayInterface(ABC):
    @property
    def monitor(self) -> int: ...

    @property
    def resolution(self) -> tuple[int, int]: ...

    def close(self, /, source) -> None: ...
    def load_cache(self, cache: str) -> None: ...
    def load_image(self, path: PathLike) -> None: ...
    def load(self, array: Union[npt.NDArray, "DisplayInterface"]) -> None: ...
    def undo(self) -> None: ...
    def clear(self) -> None: ...
    def show(self) -> None: ...
    def save(self, filename: PathLike) -> None: ...
